version: 2.1

orbs:
  docker: circleci/docker@2.0.1
  slack:  circleci/slack@3

workflows:
  docker-push-latest:
    jobs:
      - docker/publish:
          image: sue445/awscli-all
          tag: latest
          after_build:
            - slack/status
          context: DockerHub
          filters:
            branches:
              only:
                - master
